export const images = [
    {
        id: 1,
        img: 'https://i.ibb.co/ww7fv3Q/uj1.png'
    },
    {
        id: 2,
        img: 'https://i.ibb.co/NTQJqdy/POVRATAK-U-SKOLU-2.png'
    },
    {
        id: 3,
        img: 'https://i.ibb.co/ZKLrMMC/POVRATAK-U-SKOLU-4.png'
    }
]
export const smallImages = [
    {
        id:1,
        img:'https://i.ibb.co/SQM72NR/uj1-kicsi.png'
    },
    {
        id:2,
        img:'https://i.ibb.co/JQbLbJf/regi2-kicsi.png'
    },
    {
        id:3,
        img: 'https://i.ibb.co/x62Brwg/regi3-kicsi.png'
    }
]
export const Novo = [
    {
        id:1,
        name: 'POVERENJE',
        price: 1079,
        realPrice: 1199,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/380233.jpg',
        autor: 'Ernan Dijaz',
        izdavac: 'STELA KNJIGE',
        popust: 10,
        booktok: false,
        type: 'ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id:2,
        name: 'DOBILI STE SEMA TikTok Hit',
        price: 849,
        realPrice: 999,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/380051_w.jpg',
        autor: 'Dastin Tao',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 15,
        booktok: true,
        type: 'LJUBAVNI ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id:3,
        name: 'SKRIVANJE',
        price: 989,
        realPrice: 1099,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/372682_w.jpg',
        autor: 'Penelopi Daglas',
        izdavac: 'STELA KNJIGE',
        popust: 10,
        booktok: false,
        type: 'LJUBAVNI ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id:4,
        name: 'I DA SVEMU DOĐE KRAJ',
        price: 1104,
        realPrice: 1299,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/27017.jpg',
        autor: 'Jens Liljestrand',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 15,
        booktok: false,
        type: 'ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id:5,
        name: 'SAVRŠENSTVA',
        price: 712,
        realPrice: 792,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/379917_w.jpg',
        autor: 'Vinčenco Latroniko',
        izdavac: 'BOOKA',
        popust: 10,
        booktok: false,
        type: 'LJUBAVNI ROMAN ',
        quantity: 1,
        favourite: false
    },
    {
        id:6,
        name: 'TROJE',
        price: 999,
        realPrice: 1099,
        img: 'https://geopoetika.mpanel.app/storage/files/images/troje.jpg',
        autor: 'Džulijan Barns',
        izdavac: 'GEOPOETIKA',
        popust: 5,
        booktok: false,
        type: 'LJUBAVNI ROMAN ',
        quantity: 1,
        favourite: false
    },
    {
        id:7,
        name: 'OBEĆAJ MI DA ĆEŠ VOLETI',
        price: 841,
        realPrice: 999,
        img: 'https://www.vulkani.rs/files/thumbs/files/images/slike_proizvoda/thumbs_1200/28281_1200_1200px.jpg',
        autor: 'Miki Bramer',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 15,
        booktok: false,
        type: 'LJUBAVNI ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id:8,
        name: 'KANON POTIŠTENOG UMA',
        price: 764,
        realPrice: 899,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/380255.jpg',
        autor: 'Filip Grbić',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 15,
        booktok: false,
        type: 'DOMAĆI ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id:9,
        name: 'PSOVANJE PUBLIKE',
        price: 1799,
        realPrice: 1999,
        img: 'https://www.laguna.rs/_img/korice/5974/psovanje_publike_v.png',
        autor: 'Peter Handke',
        izdavac: 'LAGUNA',
        popust: 10,
        booktok: false,
        type: 'LJUBAVNI ROMAN ',
        quantity: 1,
        favourite: false
    }
]
export const Top = [
    {
        id:1,
        name: 'ANŽELIK',
        price: 849,
        realPrice: 999,
        img: 'https://www.vulkani.rs/files/images/Gijom-Muso-%E2%80%93-Anzelik_SAJT.jpg',
        autor: 'Gijom Muso',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 15,
        booktok: false,
        type: 'TRILERI/MISTERIJE',
        quantity: 1,
        favourite: false
    },
    {
        id:2,
        name: 'DOK SE KAFA NE OHLADI TikTok Hit',
        price: 931,
        realPrice: 1099,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/368175.jpg',
        autor: 'Tošikazu Kavaguči',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 15,
        booktok: true,
        type: 'LJUBAVNI ROMAN ',
        quantity: 1,
        favourite: false
    },
    {
        id:3,
        name: 'ATOMSKE NAVIKE',
        price: 1089,
        realPrice: 1209,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/335516.jpg',
        autor: 'Džejms Klir',
        izdavac: 'FINESA',
        popust: 10,
        booktok: false,
        type: 'SAVETI ZA KARIJERU I POSTIZANJE USPEHA',
        quantity: 1,
        favourite: false
    },
    {
        id:4,
        name: 'SAMO JE TEBE VREDELO SRESTI',
        price: 1079,
        realPrice: 1199,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/377323_w.jpg',
        autor: 'Vesna Dedić',
        izdavac: 'DEDIĆ',
        popust: 10,
        booktok: false,
        type: 'DOMAĆI LJUBAVNI ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id:5,
        name: 'SAZVEŽĐE SVITACA',
        price: 1079,
        realPrice: 1199,
        img: 'https://www.delfi.rs/_img/artikli/2023/04/sazvezdje_svitaca_vv.jpg',
        autor: 'Mirjana Bobić Mojsilović',
        izdavac: 'LAGUNA',
        popust: 10,
        booktok: false,
        type: 'DOMAĆI LJUBAVNI ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id:6,
        name: 'BLANK',
        price: 1298,
        realPrice: 1499,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/354711_w.jpg',
        autor: 'Feđa Štukan',
        izdavac: 'ČIGOJA ŠTAMPA',
        popust: 10,
        booktok: false,
        type: 'DOMAĆI ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id:7,
        name: '48 ZAKONA MOĆI',
        price: 809,
        realPrice: 899,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/296713.jpg',
        autor: 'Robert Grin',
        izdavac: 'KONTRAST',
        popust: 10,
        booktok: false,
        type: 'SAVETI ZA KARIJERU I POSTIZANJE USPEHA',
        quantity: 1,
        favourite: false
    },
    {
        id:8,
        name: 'NOĆNA IGRA',
        price: 849,
        realPrice: 999,
        img: 'https://www.vulkani.rs/files/images/Nora-Roberts-Nocna-igra_SAJT.jpg',
        autor: 'Nora Roberts',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 15,
        booktok: false,
        type: 'LJUBAVNI ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id:9,
        name: 'TVOJ GREH TikTok Hit',
        price: 934,
        realPrice: 1099,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/376152.jpg',
        autor: 'Mersedes Ron',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 15,
        booktok: true,
        type: 'LJUBAVNI ROMAN',
        quantity: 1,
        favourite: false
    }
]
export const TopEng = [
    {
        id:1,
        name: 'HAPPY PLACE TikTok Hit',
        price: 2149,
        realPrice: 2530,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/377348_w_1200_1200px.jpg.webp',
        autor: 'Emily Henry',
        izdavac: 'PENGUIN',
        popust: 15,
        booktok: true,
        type: 'CONTEMPORARY FICTION',
        quantity: 1,
        favourite: false
    },
    {
        id:2,
        name: 'TOO LATE TikTok Hit',
        price: 1355,
        realPrice: 1595,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/378575_w.jpg',
        autor: 'Colleen Hoover',
        izdavac: 'LITTLE BROWN',
        popust: 15,
        booktok: true,
        type: 'CRIME, THRILLERS & MYSTERY',
        quantity: 1,
        favourite: false
    },
    {
        id:3,
        name: 'LOVE THEORETICALLY TikTok Hit',
        price: 1444,
        realPrice: 1699,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/378171_w.jpg',
        autor: 'Ali Hazelwood',
        izdavac: 'LITTLE BROWN',
        popust: 15,
        booktok: true,
        type: 'CONTEMPORARY FICTION',
        quantity: 1,
        favourite: false
    },
    {
        id:4,
        name: 'ICEBREAKER TikTok Hit',
        price: 1262,
        realPrice: 1485,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/374485_w.jpg',
        autor: 'Hannah Grace',
        izdavac: 'SIMON&SHUSTER',
        popust: 15,
        booktok: true,
        type: 'YOUNG ADULT LITERATURE & FICTION',
        quantity: 1,
        favourite: false
    },
    {
        id:5,
        name: 'THE LITTLE BOOK OF BURBERRY',
        price: 2057,
        realPrice: 2420,
        img: 'https://target.scene7.com/is/image/Target/GUEST_4783e6f4-5c6f-4fa9-8916-67a7fa7dc3d4?wid=488&hei=488&fmt=pjpeg',
        autor: 'Darla-Jane Gilroy',
        izdavac: 'CARLTON BOOKS',
        popust: 15,
        booktok: false,
        type: 'FASHION',
        quantity: 1,
        favourite: false
    },
    {
        id:6,
        name: 'TIME SHELTER',
        price: 1444,
        realPrice: 1699,
        img: 'https://upload.wikimedia.org/wikipedia/en/6/68/Time_Shelter_cover.jpg',
        autor: 'Georgi Gospodinov',
        izdavac: 'ORION',
        popust: 15,
        booktok: false,
        type: 'CONTEMPORARY FICTION',
        quantity: 1,
        favourite: false
    },
    {
        id:7,
        name: 'THE PSYCHOLOGY BOOK',
        price: 2795,
        realPrice: 3289,
        img: 'https://m.media-amazon.com/images/I/81LDP+GDKVL._AC_UF1000,1000_QL80_.jpg',
        autor: 'DK',
        izdavac: 'DK',
        popust: 15,
        booktok: false,
        type: 'PSIHOLOGY',
        quantity: 1,
        favourite: false
    },
    {
        id:8,
        name: 'GOTHIKANA',
        price: 1355,
        realPrice: 1595,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/375333_w.jpg',
        autor: 'RuNyx',
        izdavac: 'SIMON&SHUSTER',
        popust: 15,
        booktok: false,
        type: 'FANTASY',
        quantity: 1,
        favourite: false
    },
    {
        id:9,
        name: 'VIOLET BENT BACKWARDS OVER THE GRASS',
        price: 2431,
        realPrice: 2860,
        img: 'https://m.media-amazon.com/images/I/71xG3fBt3-L._AC_UF1000,1000_QL80_.jpg',
        autor: 'Lana Del Rey',
        izdavac: 'SIMON&SHUSTER',
        popust: 15,
        booktok: false,
        type: 'POETRY',
        quantity: 1,
        favourite: false
    }
]
export const Stephen = [
    {
        id:1,
        name: 'CUJO',
        price: 1215,
        realPrice: 1429,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/280311.jpg',
        autor: 'Stephen King',
        izdavac: 'HODDER',
        popust: 15,
        booktok: false,
        type: 'CRIME, THRILLERS & MYSTERY',
        quantity: 1,
        favourite: false
    },
    {
        id:2,
        name: 'IT',
        price: 1542,
        realPrice: 1815,
        img: 'https://www.dymocks.com.au/Pages/ImageHandler.ashx?q=9781444707861&w=&h=570',
        autor: 'Stephen King',
        izdavac: 'HODDER',
        popust: 15,
        booktok: false,
        type: 'CRIME, THRILLERS & MYSTERY',
        quantity: 1,
        favourite: false
    },
    {
        id:3,
        name: 'THE SHINING',
        price: 1309,
        realPrice: 1540,
        img: 'https://cdn.waterstones.com/bookjackets/large/9781/4447/9781444720723.jpg',
        autor: 'Stephen King',
        izdavac: 'HODDER',
        popust: 15,
        booktok: false,
        type: 'CRIME, THRILLERS & MYSTERY',
        quantity: 1,
        favourite: false
    },
    {
        id:4,
        name: 'THE OUTSIDER',
        price: 1215,
        realPrice: 1429,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/344421_w.jpg',
        autor: 'Stephen King',
        izdavac: 'HODDER',
        popust: 15,
        booktok: false,
        type: 'CRIME, THRILLERS & MYSTERY',
        quantity: 1,
        favourite: false
    },
    {
        id:5,
        name: 'FIRESTARTER',
        price: 1262,
        realPrice: 1485,
        img: 'https://www.hachette.com.au/content/books/9781444708103.jpg',
        autor: 'Stephen King',
        izdavac: 'HODDER',
        popust: 15,
        booktok: false,
        type: 'CRIME, THRILLERS & MYSTERY',
        quantity: 1,
        favourite: false
    },
    {
        id:6,
        name: 'DREAMCATCHER',
        price: 1309,
        realPrice: 1539,
        img: 'https://m.media-amazon.com/images/I/6128c1U2VvL.jpg',
        autor: 'Stephen King',
        izdavac: 'HODDER',
        popust: 15,
        booktok: false,
        type: 'CRIME, THRILLERS & MYSTERY',
        quantity: 1,
        favourite: false
    },
    {
        id:7,
        name: 'THINNER',
        price: 1309,
        realPrice: 1539,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/255069_w.jpg',
        autor: 'Stephen King',
        izdavac: 'HODDER',
        popust: 15,
        booktok: false,
        type: 'CRIME, THRILLERS & MYSTERY',
        quantity: 1,
        favourite: false
    },
    {
        id:8,
        name: 'BILLY SUMMERS',
        price: 1215,
        realPrice: 1429,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/367396.jpg',
        autor: 'Stephen King',
        izdavac: 'HODDER',
        popust: 15,
        booktok: false,
        type: 'CRIME, THRILLERS & MYSTERY',
        quantity: 1,
        favourite: false
    },
    {
        id:9,
        name: 'THE STAND',
        price: 1402,
        realPrice: 1649,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/353182.jpg',
        autor: 'Stephen King',
        izdavac: 'HODDER',
        popust: 15,
        booktok: false,
        type: 'CRIME, THRILLERS & MYSTERY',
        quantity: 1,
        favourite: false
    }
]
export const do40 = [
    {
        id:1,
        name: 'DAMIN GAMBIT',
        price: 719,
        realPrice: 1199,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/26296.jpg',
        autor: 'Volter Tevis',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 40,
        booktok: false,
        type: 'ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id:2,
        name: 'GRČKO BLAGO',
        price: 899,
        realPrice: 1499,
        img: 'https://www.vulkani.rs/files/thumbs/files/images/slike_proizvoda/thumbs_1200/23889_1200_1200px.jpg',
        autor: 'Irving Stoun',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 40,
        booktok: false,
        type: 'ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id:3,
        name: 'KUĆA GOLDENOVIH',
        price: 719,
        realPrice: 1199,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/316491.jpg',
        autor: 'Salman Ruždi',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 40,
        booktok: false,
        type: 'ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id:4,
        name: 'DEVOJKA IZ BRUKLINA',
        price: 599,
        realPrice: 999,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/23459.jpg',
        autor: 'Gijom Muso',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 40,
        booktok: false,
        type: 'LJUBAVNI ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id:5,
        name: 'PONOVO SVOJA',
        price: 599,
        realPrice: 999,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/23501.jpg',
        autor: 'Nora Roberts',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 40,
        booktok: false,
        type: 'LJUBAVNI ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id:6,
        name: 'DEVETA KUĆA TikTok Hit',
        price: 779,
        realPrice: 1299,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/378584.jpg',
        autor: 'Li Bardugo',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 40,
        booktok: true,
        type: 'FANTASTIKA',
        quantity: 1,
        favourite: false
    },
    {
        id:7,
        name: 'GOSPODAR PRSTENOVA I Družina Prstena',
        price: 1740,
        realPrice: 2320,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/326847_w.jpg',
        autor: 'Džon Ronald Rejel Tolkin',
        izdavac: 'PUBLIK PRAKTIKUM',
        popust: 25,
        booktok: false,
        type: 'FANTASTIKA',
        quantity: 1,
        favourite: false
    },
    {
        id:8,
        name: 'HOBIT',
        price: 824,
        realPrice: 1099,
        img: 'https://m.media-amazon.com/images/I/710+HcoP38L._AC_UF1000,1000_QL80_.jpg',
        autor: 'Džon Ronald Rejel Tolkin',
        izdavac: 'PUBLIK PRAKTIKUM',
        popust: 25,
        booktok: false,
        type: 'FANTASTIKA',
        quantity: 1,
        favourite: false
    },
    {
        id:9,
        name: 'USPON MRAKA Knjiga I TikTok Hit',
        price: 479,
        realPrice: 719,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/366052_w.jpg',
        autor: 'K. S. Pakat',
        izdavac:  'VULKAN IZDAVAŠTVO',
        popust: 40,
        booktok: true,
        type: 'FANTASTIKA',
        quantity: 1,
        favourite: false
    }
]
export const Popularna = [
    {
        id:1,
        name: '36 PITANJA koja su mi promenila mišljenje o tebi',
        price: 499,
        realPrice: 999,
        img: 'https://www.vulkani.rs/files/thumbs/files/images/slike_proizvoda/thumbs_1200/23987_1200_1200px.jpg',
        autor: 'Viki Grant',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 50,
        booktok: false,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 2,
        name: 'AMERIČKA DINASTIJA TikTok Hit',
        price: 549,
        realPrice: 1099,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/342218_w_1200_1200px.jpg.webp',
        autor: 'Ketrin Makgi',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 50,
        booktok: true,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 3,
        name: 'APLAUZ',
        price: 499,
        realPrice: 999,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/23974.jpg',
        autor: 'Hejli Barker',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 50,
        booktok: false,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },    
    {
        id: 4,
        name: 'CARSTVO PESKA',
        price: 499,
        realPrice: 999,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/319753_w.jpg',
        autor: 'Kejla Olson',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 50,
        booktok: false,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 5,
        name: 'KRALJICA OGNJA',
        price: 549,
        realPrice: 1099,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/23640.jpg',
        autor: 'Lora Sebastijan',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 50,
        booktok: false,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 6,
        name: 'DRANGULIJE',
        price: 499,
        realPrice: 899,
        img: 'https://www.vulkani.rs/files/thumbs/files/images/slike_proizvoda/thumbs_1200/24560_1200_1200px.jpg',
        autor: 'Kersten Smit',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 50,
        booktok: false,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 7,
        name: 'GOSPA OD DIMA',
        price: 499,
        realPrice: 999,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/23641.jpg',
        autor: 'Lora Sebastijan',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 50,
        booktok: false,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 8,
        name: 'I ONDA ME TAMA OBUZME',
        price: 499,
        realPrice: 999,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/23643.jpg',
        autor: 'Kirsten Vajt',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 50,
        booktok: false,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 9,
        name: 'ISKRA U PEPELU',
        price: 499,
        realPrice: 999,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/285232.jpg',
        autor: 'Saba Tahir',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 50,
        booktok: false,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    }
]
export const Za500 = [
    {
        id:1,
        name: 'SREĆNA PORODICA KALUĐERA KOJI JE PRODAO SVOJ FERARI',
        price: 499,
        realPrice: 899,
        img: 'https://www.vulkani.rs/files/thumbs/files/images/slike_proizvoda/thumbs_1200/23204_1200_1200px.jpg',
        autor: 'Robin S. Šarma',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 44,
        booktok: false,
        type: 'ASERTIVNOST, MOTIVACIJA I SAMOPOŠTOVANJE',
        quantity: 1,
        favourite: false
    },
    {
        id: 2,
        name: 'ČETIRI ŽENE IZ ISTANBULA',
        price: 499,
        realPrice: 999,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/24599.jpg',
        autor: 'Ajše Kulin',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 50,
        booktok: false,
        type: 'ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 3,
        name: 'ČOVEK BEZ GRANICA',
        price: 499,
        realPrice: 999,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/357440.jpg',
        autor: 'Ričard Č. Morais',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 50,
        booktok: false,
        type: 'ROMAN',
        quantity: 1,
        favourite: false
    },    
    {
        id: 4,
        name: 'IDI KUDA TE SRCE VODI',
        price: 499,
        realPrice: 899,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/24864.jpg',
        autor: 'Kejla Olson',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 44,
        booktok: false,
        type: 'ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 5,
        name: 'KAPLJICA SREĆE',
        price: 499,
        realPrice: 899,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/25310.jpg',
        autor: 'Antoan Loren',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 44,
        booktok: false,
        type: 'ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 6,
        name: 'RATNIK MUDROSTI',
        price: 499,
        realPrice: 999,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/22496.jpg',
        autor: 'Tomas Miler',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 50,
        booktok: false,
        type: 'ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 7,
        name: 'SOFIJA',
        price: 499,
        realPrice: 899,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/23952.jpg',
        autor: 'Katerina Bonvičini',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 44,
        booktok: false,
        type: 'ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 8,
        name: 'DEVOJKA SA LJUBIČICAMA',
        price: 499,
        realPrice: 999,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/26064.jpg',
        autor: 'Eloiza Džejms',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 50,
        booktok: false,
        type: 'LJUBAVNI ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 9,
        name: 'OSTRVO ČUDA',
        price: 499,
        realPrice: 999,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/24866.png',
        autor: 'Nora Roberts',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 50,
        booktok: false,
        type: 'LJUBAVNI ROMAN',
        quantity: 1,
        favourite: false
    }
]
export const NovoIzdBooks = [
    {
        id:1,
        name: 'ARISTOTEL I DANTE Uranjaju u vode sveta TikTok Hit',
        price: 1079,
        realPrice: 1199,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/380758.jpg',
        autor: 'Bendžamin Alire Saenz',
        izdavac: 'PUBLIK PRAKTIKUM',
        popust: 10,
        booktok: true,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 2,
        name: 'TAJNA FORMULA STVARANJA',
        price: 799,
        realPrice: 719,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/380757_w_1200_1200px.jpg.webp',
        autor: 'Ostin Kleon',
        izdavac: 'HARMONIJA KNJIGE',
        popust: 10,
        booktok: false,
        type: 'ASERTIVNOST, MOTIVACIJA I SAMOPOŠTOVANJE',
        quantity: 1,
        favourite: false
    },
    {
        id: 3,
        name: 'ŽUTE OČI KROKODILA',
        price: 1079,
        realPrice: 1199,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/380756_w_1200_1200px.jpg.webp',
        autor: 'Katrin Pankol',
        izdavac: 'STELA KNJIGE',
        popust: 10,
        booktok: false,
        type: 'CHICK LIT - ROMANTIČNA KOMEDIJA',
        quantity: 1,
        favourite: false
    },    
    {
        id: 4,
        name: 'ZAKUCAVANJE ZA VEČNOST: MAJKL DŽORDAN I SVET KOJI JE STVORIO',
        price: 1189,
        realPrice: 1399,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/26380.jpg',
        autor: 'Dejvid Halberstam',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 15,
        booktok: false,
        type: 'BIOGRAFIJE, MEMOARI, DNEVNICI, PISMA',
        quantity: 1,
        favourite: false
    },
    {
        id: 5,
        name: 'NA SIGURNOM MESTU',
        price: 934,
        realPrice: 1099,
        img: 'https://www.vulkani.rs/files/images/slike_proizvoda/26983.jpg',
        autor: 'Volas Stegner',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 15,
        booktok: false,
        type: 'ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 6,
        name: 'VESELI BROD',
        price: 594,
        realPrice: 699,
        img: 'https://www.vulkani.rs/files/thumbs/files/images/slike_proizvoda/thumbs_1200/29168_1200_1200px.jpg',
        autor: 'Slobodan Stanišić',
        izdavac: 'VULKAN IZDAVAŠTVO',
        popust: 15,
        booktok: false,
        type: 'ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 7,
        name: 'OJAČAJ SAMOPOUZDANJE',
        price: 809,
        realPrice: 899,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/380686_w.jpg',
        autor: 'Štefani Štal',
        izdavac: 'LAGUNA',
        popust: 10,
        booktok: false,
        type: 'ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 8,
        name: 'APSOLUTNA ISTINA',
        price: 1619,
        realPrice: 1799,
        img: 'https://www.delfi.rs/_img/artikli/2023/08/apsolutna_istina_vv.jpg',
        autor: 'Majk Tajson',
        izdavac: 'LAGUNA',
        popust: 10,
        booktok: false,
        type: 'BIOGRAFIJE, MEMOARI, DNEVNICI, PISMA',
        quantity: 1,
        favourite: false
    },
    {
        id: 9,
        name: 'MALIBU U PLAMENU TikTok Hit',
        price: 1079,
        realPrice: 1199,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/380680_w_1200_1200px.jpg.webp',
        autor: 'Tejlor Dženkins Rid',
        izdavac: 'LAGUNA',
        popust: 10,
        booktok: true,
        type: 'ROMAN',
        quantity: 1,
        favourite: false
    }
]
export const TiktokHit1 = [
    {
        id:1,
        name: 'DVOR SREBRNIH PLAMENOVA TikTok Hit',
        price: 1187,
        realPrice: 1318,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/380095_w.jpg',
        autor: 'Sara Dž. Mas',
        izdavac: 'URBAN READS',
        popust: 10,
        booktok: true,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 2,
        name: 'DVOR KRILA I PROPASTI TikTok Hit',
        price: 1169,
        realPrice: 1299,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/371259.jpg',
        autor: 'Sara Dž. Mas',
        izdavac: 'URBAN READS',
        popust: 10,
        booktok: true,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 3,
        name: 'DVOR MAGLE I SRDŽBE TikTok Hit',
        price: 1079,
        realPrice: 1199,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/368263.jpg',
        autor: 'Sara Dž. Mas',
        izdavac: 'URBAN READS',
        popust: 10,
        booktok: true,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },    
    {
        id: 4,
        name: 'ARISTOTEL I DANTE Uranjaju u vode sveta TikTok Hit        ',
        price: 1079,
        realPrice: 1199,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/380758.jpg',
        autor: 'Bendžamin Alire Saenz',
        izdavac: 'PUBLIK PRAKTIKUM',
        popust: 10,
        booktok: true,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 5,
        name: 'ŠEST VRANA I DEO DUOLOGIJE TikTok Hit',
        price: 1079,
        realPrice: 1199,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/294604_w_1200_1200px.jpg.webp',
        autor: 'Li Bardugo',
        izdavac: 'URBAN READS',
        popust: 10,
        booktok: true,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 6,
        name: 'DVOR TRNJA I RUŽA TikTok hit',
        price: 1079,
        realPrice: 1199,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/360496_w_1200_1200px.jpg.webp',
        autor: 'Sara Dž. Mas',
        izdavac: 'URBAN READS',
        popust: 10,
        booktok: true,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 7,
        name: 'PODLI KRALJ TikTok Hit',
        price: 989,
        realPrice: 1099,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/359488_w.jpg',
        autor: 'Holi Blek',
        izdavac: 'PUBLIK PRAKTIKUM',
        popust: 10,
        booktok: true,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 8,
        name: 'KRALJICA NIČEGA TikTok Hit',
        price: 989,
        realPrice: 1099,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/364171.jpg',
        autor: 'Holi Blek',
        izdavac: 'PUBLIK PRAKTIKUM',
        popust: 10,
        booktok: true,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    },
    {
        id: 9,
        name: 'LETO KADA SAM POSTALA LEPA TikTok Hit',
        price: 989,
        realPrice: 1099,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/369665_w_1200_1200px.jpg.webp',
        autor: 'Dženi Han',
        izdavac: 'URBAN READS',
        popust: 10,
        booktok: true,
        type: 'TINEJDŽ I YA ROMAN',
        quantity: 1,
        favourite: false
    }
]
export const TiktokHit2 = [
    {
        id:1,
        name: 'MR WRONG NUMBER TikTok Hit',
        price: 1355,
        realPrice: 1595,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/366058_w.jpg',
        autor: 'Lynn Painter',
        izdavac: 'PENGUIN',
        popust: 15,
        booktok: true,
        type: 'ROMANTIC COMEDY',
        quantity: 1,
        favourite: false
    },
    {
        id: 2,
        name: 'LOATHE TO LOVE YOU TikTok Hit',
        price: 1215,
        realPrice: 1430,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/373502.jpg',
        autor: 'Ali Hazelwood (Ali Hejzelvud)',
        izdavac: 'LITTLE BROWN',
        popust: 15,
        booktok: true,
        type: 'CONTEMPORARY FICTION',
        quantity: 1,
        favourite: false
    },
    {
        id: 3,
        name: 'HEART BONES TikTok Hit',
        price: 2020,
        realPrice: 2599,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/373503_w.jpg',
        autor: 'Colleen Hoover (Kolin Huver)',
        izdavac: 'SIMON&SHUSTER',
        popust: 15,
        booktok: true,
        type: 'YOUNG ADULT LITERATURE & FICTION',
        quantity: 1,
        favourite: false
    },    
    {
        id: 4,
        name: 'THE UNHONEYMOONERS TikTok Hit',
        price: 1309,
        realPrice: 1540,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/365650_w.jpg',
        autor: 'Christina Lauren (Kristina Loren)',
        izdavac: 'LITTLE BROWN',
        popust: 15,
        booktok: true,
        type: 'ROMANTIC COMEDY',
        quantity: 1,
        favourite: false
    },
    {
        id: 5,
        name: 'IT HAPPENED ONE SUMMER TikTok Hit',
        price: 1355,
        realPrice: 1595,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/368555_w_1200_1200px.jpg.webp',
        autor: 'Tessa Bailey',
        izdavac: 'HARPERCOLLINS',
        popust: 15,
        booktok: true,
        type: 'ROMANTIC COMEDY',
        quantity: 1,
        favourite: false
    },
    {
        id: 6,
        name: 'ALL THE BRIGHT PLACES TikTok Hit',
        price: 1318,
        realPrice: 1551,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/283082_w_1200_1200px.jpg.webp',
        autor: 'Jennifer Niven (Dženifer Niven)',
        izdavac: 'PENGUIN',
        popust: 15,
        booktok: true,
        type: 'YOUNG ADULT LITERATURE & FICTION',
        quantity: 1,
        favourite: false
    },
    {
        id: 7,
        name: 'DAISY JONES AND THE SIX TikTok Hit',
        price: 1402,
        realPrice: 1650,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/363844_w.jpg',
        autor: 'Taylor Jenkins Reid (Tejlor Dženkins Rid)',
        izdavac: 'ARROW',
        popust: 15,
        booktok: true,
        type: 'CONTEMPORARY FICTION',
        quantity: 1,
        favourite: false
    },
    {
        id: 8,
        name: 'SEVEN HUSBANDS OF EVELYN HUGO TikTok Hit',
        price: 1309,
        realPrice: 1540,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/362824_w.jpg',
        autor: 'Taylor Jenkins Reid (Tejlor Dženkins Rid)',
        izdavac: 'SIMON&SHUSTER',
        popust: 15,
        booktok: true,
        type: 'CONTEMPORARY FICTION',
        quantity: 1,
        favourite: false
    },
    {
        id: 9,
        name: 'THE HATING GAME TikTok Hit',
        price: 989,
        realPrice: 1099,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/363874.jpg',
        autor: 'Sally Thorne',
        izdavac: 'LITTLE BROWN',
        popust: 15,
        booktok: true,
        type: 'CONTEMPORARY FICTION',
        quantity: 1,
        favourite: false
    }
]
export const HarryPotterItems1 = [
    {
        id:1,
        name: 'Sveska B5 sa spiralom HARRY POTTER',
        price: 442,
        realPrice: 520,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/380338.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'sveske',
        quantity: 1,
        favourite: false
    },
    {
        id:2,
        name: 'HARRY POTTER premijum sveska RAVENCLAW',
        price: 1020,
        realPrice: 1200,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/380229_1_w.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'NOTESI',
        quantity: 1,
        favourite: false
    },
    {
        id:3,
        name: 'HARRY POTTER premijum sveska GRYFFINDOR',
        price: 1020,
        realPrice: 1200,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/380228_1_w.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'NOTESI',
        quantity: 1,
        favourite: false
    },
    {
        id:4,
        name: 'HARRY POTTER kišobran RAVENCLAW',
        price: 1615,
        realPrice: 1900,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/images/slike_proizvoda/thumbs_600/380225_1_600_600px.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'KIŠOBRANI',
        quantity: 1,
        favourite: false
    },
    {
        id:5,
        name: 'HARRY POTTER kišobran HUFFLEPUFF',
        price: 1615,
        realPrice: 1900,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/380224_1_w.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'KIŠOBRANI',
        quantity: 1,
        favourite: false
    },
    {
        id:6,
        name: 'HARRY POTTER kišobran GRYFFINDOR',
        price: 1615,
        realPrice: 1900,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/images/slike_proizvoda/thumbs_600/380223_1_600_600px.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'KIŠOBRANI',
        quantity: 1,
        favourite: false
    },
    {
        id:7,
        name: 'HARRY POTTER kišobran SLYTHERIN',
        price: 1615,
        realPrice: 1900,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/images/slike_proizvoda/thumbs_600/380222_1_600_600px.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'KIŠOBRANI',
        quantity: 1,
        favourite: false
    }
]
export const HarryPotterItems2 = [
    {
        id:1,
        name: 'HARRY POTTER ranac sa kolicima i tri pregrade',
        price: 6392,
        realPrice: 7990,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/379668_w_1200_1200px.jpg.webp',
        autor: '',
        izdavac: '',
        popust: 20,
        booktok: false,
        type: 'RANAC ŠKOLSKI',
        quantity: 1,
        favourite: false
    },
    {
        id:2,
        name: 'HARRY POTTER društvena igra HOGWARTS HALLWAYS        ',
        price: 6250,
        realPrice: '',
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/371228_1_w.jpg',
        autor: '',
        izdavac: '',
        popust: '',
        booktok: false,
        type: 'DRUŠTVENE IGRE',
        quantity: 1,
        favourite: false
    },
    {
        id:3,
        name: 'HARRY POTTER RAVENCLAW HOUSE BOX SET',
        price: 11220,
        realPrice: 13200,
        img: 'https://www.delfi.rs/_img/artikli/2022/04/harry_potter_ravenclaw_house_editions_paperback_box_set_vv-2.jpg',
        autor: 'J.K. Rowling',
        izdavac: 'BLOOMSBERY',
        popust: 15,
        booktok: false,
        type: 'FANTASY',
        quantity: 1
    },
    {
        id:4,
        name: 'HARRY POTTER GRYFFINDOR HOUSE BOX SET',
        price: 12155,
        realPrice: 14300,
        img: 'https://www.delfi.rs/_img/artikli/2022/04/harry_potter_gryffindor_house_editions_paperback_box_set_vv.jpg',
        autor: 'J.K. Rowling',
        izdavac: 'BLOOMSBERY',
        popust: 15,
        booktok: false,
        type: 'FANTASY',
        quantity: 1
    },
    {
        id:5,
        name: 'HARRY POTTER SLYTHERIN HOUSE BOX SET',
        price: 12155,
        realPrice: 14300,
        img: 'https://www.delfi.rs/_img/artikli/2022/04/harry_potter_slytherin_house_editions_paperback_box_set_vv.jpg',
        autor: 'J.K. Rowling',
        izdavac: 'BLOOMSBERY',
        popust: 15,
        booktok: false,
        type: 'FANTASY',
        quantity: 1,
        favourite: false
    },
    {
        id:6,
        name: 'HARRY POTTER BOXED SET adult',
        price: 9350,
        realPrice: 11000,
        img: 'https://www.delfi.rs/_img/artikli/2018/11/harry_potter_boxed_set_the_complete_collection_vv.jpg',
        autor: 'J.K. Rowling',
        izdavac: 'BLOOMSBERY',
        popust: 15,
        booktok: false,
        type: 'FANTASY',
        quantity: 1,
        favourite: false
    },
    {
        id:7,
        name: 'HARRY POTTER BOXED SET',
        price: 9836,
        realPrice: 11572,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/290946_w_1200_1200px.jpg.webp',
        autor: 'J.K. Rowling',
        izdavac: 'BLOOMSBERY',
        popust: 15,
        booktok: false,
        type: 'FANTASY',
        quantity: 1,
        favourite: false
    }
]
export const HarryPotterItems3 = [
    {
        id:1,
        name: 'HARRY POTTER novčanik RAVENCLA',
        price: 1487,
        realPrice: 1750,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/380214_1_w.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'NOVČANICI',
        quantity: 1,
        favourite: false
    },
    {
        id:2,
        name: 'HARRY POTTER novčanik HUFFLEPUFF',
        price: 1487,
        realPrice: 1750,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/380213_1_w.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'NOVČANICI',
        quantity: 1,
        favourite: false
    },
    {
        id:3,
        name: 'HARRY POTTER novčanik SLYTHERIN',
        price: 1487,
        realPrice: 1750,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/380212_1_w.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'NOVČANICI',
        quantity: 1,
        favourite: false
    },
    {
        id:4,
        name: 'HARRY POTTER novčanik GRYFFINDOR',
        price: 1487,
        realPrice: 1750,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/380211_1_w.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'NOVČANICI',
        quantity: 1,
        favourite: false
    },
    {
        id:5,
        name: 'Kutija za hranu HARRY POTTER',
        price: 1521,
        realPrice: 1790,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/379673.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'KUTIJE ZA HRANU',
        quantity: 1,
        favourite: false
    },
    {
        id:6,
        name: 'Flaša za vodu 500ml HARRY POTTER',
        price: 1147,
        realPrice: 1350,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/379670.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'FLAŠE I TERMOSI',
        quantity: 1,
        favourite: false
    },
    {
        id:7,
        name: 'HARRY POTTER školski set sa pernicom',
        price: 1402,
        realPrice: 1650,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/379672_w_1200_1200px.jpg.webp',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'ŠKOLSKI SETOVI',
        quantity: 1,
        favourite: false
    }
]
export const GiftItems1 = [
    {
        id:1,
        name: 'Flaša za vodu 0,5L CHECK',
        price: 1887,
        realPrice: 2220,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/380322_w.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'FLAŠE I TERMOSI',
        quantity: 1,
        favourite: false
    },
    {
        id:2,
        name: 'Flaša za vodu 0,5L YUMMY YUMMY',
        price: 1887,
        realPrice: 2220,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/380319_w_1200_1200px.jpg.webp',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'FLAŠE I TERMOSI',
        quantity: 1,
        favourite: false
    },
    ,
    {
        id:3,
        name: 'Staklena flaša 0,5L BEAUTIFUL LEMONS',
        price: 1402,
        realPrice: 1650,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/380310.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'FLAŠE I TERMOSI',
        quantity: 1,
        favourite: false
    },
    ,
    {
        id:4,
        name: 'Staklena flaša 0,5L BUTTERFLY FLOWERS',
        price: 1402,
        realPrice: 1650,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/380311_w.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'FLAŠE I TERMOSI',
        quantity: 1,
        favourite: false
    },
    ,
    {
        id:5,
        name: 'Staklena flaša 0,5L PAT',
        price: 1402,
        realPrice: 1650,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/380314_w.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'FLAŠE I TERMOSI',
        quantity: 1,
        favourite: false
    },
    ,
    {
        id:6,
        name: 'Šolja u poklon kutiji 0,4L PURE MEADOW ANTHRACITE',
        price: 1643,
        realPrice: 1933,
        img: 'https://www.knjizare-vulkan.rs/files/images/slike_proizvoda/380305.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'FLAŠE I TERMOSI',
        quantity: 1,
        favourite: false
    },
]
export const GiftItems2 = [
    {
        id:1,
        name: 'Kasica SKUTER',
        price: 2150,
        realPrice: '',
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/374664_w_1200_1200px.jpg.webp',
        autor: '',
        izdavac: '',
        popust: '',
        booktok: false,
        type: 'KASICE',
        quantity: 1,
        favourite: false
    },
    {
        id:2,
        name: 'Ram za slike 20X25 cm',
        price: 580,
        realPrice: 683,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/376509_w_1200_1200px.jpg.webp',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'RAMOVI ZA FOTOGRAFIJE',
        quantity: 1,
        favourite: false
    },
    ,
    {
        id:3,
        name: 'TALL ROCK VASE',
        price: 1527,
        realPrice: '',
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/371812_w.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'VAZE I ZAVESE',
        quantity: 1,
        favourite: false
    },
    ,
    {
        id:4,
        name: 'Noćna lampa GORILA',
        price: 679,
        realPrice: 799,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/372836_w.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'LAMPE',
        quantity: 1,
        favourite: false
    },
    ,
    {
        id:5,
        name: 'Noćna lampa VATROGASNA KOLA',
        price: 1869,
        realPrice: 2199,
        img: 'https://www.knjizare-vulkan.rs/files/watermark/files/images/slike_proizvoda/thumbs_w/372840_w.jpg',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'LAMPE',
        quantity: 1,
        favourite: false
    },
    ,
    {
        id:6,
        name: 'Ukrasna kutijica SRCE',
        price: 122,
        realPrice: 144,
        img: 'https://www.knjizare-vulkan.rs/files/thumbs/files/watermark/files/images/slike_proizvoda/thumbs_w/thumbs_1200/322512_w_1200_1200px.jpg.webp',
        autor: '',
        izdavac: '',
        popust: 15,
        booktok: false,
        type: 'UKRASNE KUTIJICE',
        quantity: 1,
        favourite: false
    },
]
export const Hoover = [
    {
        id:1,
        img:'https://i.ibb.co/1q8MXwK/C89116-1.png'
    },
    {
        id:2,
        img:'https://i.ibb.co/2dWmQY7/Untitled-design-18.png',
    }
]
export const Manga = [
    {
        id:1,
        img:'https://i.ibb.co/PCvdTKZ/MANGA.png'
    },
    {
        id:2,
        img:'https://i.ibb.co/MDpbbm7/Untitled-design-19.png',
    }
]
export const AkcijaImage = [
    {
        id: 1,
        img: 'https://i.ibb.co/w6JqH55/cold-smooth-tasty.png'
    },
    {
        id: 2,
        img: 'https://i.ibb.co/5nMFryT/Untitled-design-20.png'
    },
]
export const Aleksandro = [
    {
        id: 1,
        img: 'https://i.ibb.co/KFXZZR2/ALE.png'
    },
    {
        id: 2,
        img: 'https://i.ibb.co/0r80Qwv/alesandro-BARIKO.png'
    },
]
export const NovaIzdaImg = [
    {
        id: 1,
        img: 'https://i.ibb.co/fNfjNxW/NOVA.png'
    },
    {
        id: 2,
        img: 'https://i.ibb.co/hWSrP9M/Untitled-design-21.png'
    },
]
export const BookTokImg = [
    {
        id: 1,
        img: 'https://i.ibb.co/C9JbdK4/NOVA-1.png'
    },
    {
        id: 2,
        img: 'https://i.ibb.co/s5bFPjJ/Untitled-design-22.png'
    },
]
export const HarryPotterImg = [
    {
        id: 1,
        img: 'https://i.ibb.co/hypgYJT/NOVA-2.png'
    },
    {
        id: 2,
        img: 'https://i.ibb.co/JjkyNXD/Untitled-design-23.png'
    },
]
export const EnglishBooksImg = [
    {
        id: 1,
        img: 'https://i.ibb.co/hBM6699/FICTION.png'
    },
    {
        id: 2,
        img: 'https://i.ibb.co/cySN7fL/Untitled-design-24.png'
    },
]
export const FlaseImg = [
    {
        id: 1,
        img: 'https://i.ibb.co/KVHm2Xq/FICTION-1.png'
    },
    {
        id: 2,
        img: 'https://i.ibb.co/h8PLX4k/Untitled-design-25.png'
    },
]
export const bankImages = [
    {
        id:1,
        img: 'https://www.knjizare-vulkan.rs/files/images/card/maestro50.gif'
    },
    {
        id:2,
        img: 'https://www.knjizare-vulkan.rs/files/images/card/amex.jpg.webp'
    },
    {
        id:3,
        img: 'https://www.knjizare-vulkan.rs/files/images/card/Visa50.gif'
    },
    {
        id:4,
        img: 'https://www.knjizare-vulkan.rs/files/images/card/dinacard50.png.webp'
    },
    {
        id:5,
        img: 'https://www.knjizare-vulkan.rs/files/images/card/wsPay.png.webp'
    },
    {
        id:6,
        img: 'https://www.nirapress.com/wp-content/uploads/2022/10/LOGO-BANCA-INTESA.png'
    },
    {
        id:7,
        img: 'https://www.knjizare-vulkan.rs/files/images/card/verifiedbyvisa.png.webp'
    },
    {
        id:8,
        img: 'https://www.knjizare-vulkan.rs/files/images/card/masterCardSC.png.webp'
    },
    {
        id:9,
        img: 'https://www.knjizare-vulkan.rs/files/images/card/ips_logo.jpg.webp'
    },
    {
        id:10,
        img: 'https://www.knjizare-vulkan.rs/files/images/card/raiffeisen_logo.png.webp'
    },
]
export const EuropeanCountryNames = [
    { name: "Albania" },
    { name: "Andorra" },
    { name: "Austria" },
    { name: "Belarus" },
    { name: "Belgium" },
    { name: "Bosnia and Herzegovina" },
    { name: "Bulgaria" },
    { name: "Croatia" },
    { name: "Cyprus" },
    { name: "Czech Republic" },
    { name: "Denmark" },
    { name: "Estonia" },
    { name: "Finland" },
    { name: "France" },
    { name: "Germany" },
    { name: "Greece" },
    { name: "Hungary" },
    { name: "Iceland" },
    { name: "Ireland" },
    { name: "Italy" },
    { name: "Kosovo" },
    { name: "Latvia" },
    { name: "Liechtenstein" },
    { name: "Lithuania" },
    { name: "Luxembourg" },
    { name: "Malta" },
    { name: "Moldova" },
    { name: "Monaco" },
    { name: "Montenegro" },
    { name: "Netherlands" },
    { name: "North Macedonia" },
    { name: "Norway" },
    { name: "Poland" },
    { name: "Portugal" },
    { name: "Romania" },
    { name: "Russia" },
    { name: "San Marino" },
    { name: "Serbia" },
    { name: "Slovakia" },
    { name: "Slovenia" },
    { name: "Spain" },
    { name: "Sweden" },
    { name: "Switzerland" },
    { name: "Ukraine" },
    { name: "United Kingdom" },
    { name: "Vatican City" }
  ];
export default images